In [15]:
import numpy as np
import pandas as pd
import random
from sklearn import preprocessing

In [3]:
df = pd.read_csv("latest_data.csv")

In [6]:
df.head(5)

user    dish_ordered  day       time  veg   place
0  user_418      kaju barfi  wed  breakfast  yes  office
1  user_566     momo burger  sun      lunch  yes  office
2   user_42   rustica pizza  fri  breakfast  yes    home
3  user_376   mashed potato  fri  breakfast  yes    home
4  user_795  skillet cookie  mon     dinner  yes  office

In [5]:
del df['Unnamed: 0']

In [8]:
dict_of_data = {k: v for k, v in df.groupby('user')}

In [12]:
user_df = dict_of_data['user_1']

In [14]:
user_df.head(5)

user       dish_ordered  day    time  veg place
6226   user_1    pili pili pizza  sat  dinner  yes  home
7140   user_1             malpua  sun  dinner  yes  home
7636   user_1  paneer manchurian  sat  dinner  yes  home
10392  user_1    achari mushroom  fri  dinner  yes  home
10449  user_1     peri peri wrap  fri   lunch  yes  home

In [13]:
len(user_df)

91

In [16]:
le = preprocessing.LabelEncoder()

In [17]:
veg_encd = le.fit_transform(user_df['veg'])
le_veg_mapping = dict(zip(le.classes_, le.transform(le.classes_)))

In [18]:
dish_ordered_encd = le.fit_transform(user_df['dish_ordered'])
le_dish_mapping = dict(zip(le.transform(le.classes_),le.classes_))
le_dish_mapping_rf = dict(zip(le.classes_, le.transform(le.classes_)))

In [19]:
time_encd = le.fit_transform(user_df['time'])
le_time_mapping = dict(zip(le.classes_, le.transform(le.classes_)))

In [20]:
day_encd = le.fit_transform(user_df['day'])
le_day_mapping = dict(zip(le.classes_, le.transform(le.classes_)))

In [41]:
place_encd = le.fit_transform(user_df['place'])
le_place_mapping = dict(zip(le.classes_, le.transform(le.classes_)))

In [42]:
liked_encd = le.fit_transform(user_df['liked'])
le_liked_mapping = dict(zip(le.classes_, le.transform(le.classes_)))

In [24]:
listt = ['yes','no']

In [23]:
import random

In [25]:
liked = random.choices(listt, k=91)

In [27]:
#liked

In [28]:
user_df['liked'] = liked

In [29]:
user_df.head(5)

user       dish_ordered  day    time  veg place liked
6226   user_1    pili pili pizza  sat  dinner  yes  home    no
7140   user_1             malpua  sun  dinner  yes  home   yes
7636   user_1  paneer manchurian  sat  dinner  yes  home   yes
10392  user_1    achari mushroom  fri  dinner  yes  home   yes
10449  user_1     peri peri wrap  fri   lunch  yes  home   yes

In [30]:
list2 = zip(time_encd,day_encd,place_encd)
features=list(list2)

In [56]:
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

In [32]:
model=GaussianNB()

In [33]:
model.fit(features,dish_ordered_encd)

GaussianNB(priors=None, var_smoothing=1e-09)

In [34]:
predicted = model.predict([[le_time_mapping['breakfast'],le_day_mapping['mon'],le_place_mapping['office']]])

In [35]:
le_dish_mapping[predicted.item()]

'dahi papadi chaat'

In [36]:
predicted

array([19])

In [37]:
predicted =model.predict_proba([[le_time_mapping['breakfast'],le_day_mapping['wed'],le_place_mapping['office']]])

In [38]:
p = np.argsort(-predicted)
recommend= {}
for i in range(0,5):
    recommend[le_dish_mapping[p[0,i]]] = predicted[0,p[0,i]]

recommend

{'andhra chilli chicken': 0.4999999999887494,
 'berryblast': 0.4999999999887494,
 'rich chicken broth': 1.582079721785505e-11,
 'smoked chicken sandwich': 6.5950894874877284e-12,
 'chicken frankie': 8.64369043533659e-14}

In [39]:
list3 = zip(time_encd,day_encd,place_encd)
features=list(list3)

In [43]:
model2=GaussianNB()
model2.fit(features,liked_encd)

GaussianNB(priors=None, var_smoothing=1e-09)

In [44]:
predicted2 =model2.predict_proba([[le_time_mapping['breakfast'],le_day_mapping['wed'],le_place_mapping['office']]])

In [45]:
predicted2 #probability of ordering at this time place and day

array([[0.6734483, 0.3265517]])

In [46]:
le_liked_mapping

{'no': 0, 'yes': 1}

In [47]:
############################

In [48]:
list4 = zip(time_encd,dish_ordered_encd)
features=list(list4)

In [58]:
#model3=GaussianNB()
#model3.fit(features,liked_encd)

model3 = RandomForestClassifier()
model3.fit(features,liked_encd)

C:\Users\mahaj\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [59]:
predicted3 =model3.predict_proba([[le_time_mapping['breakfast'],le_dish_mapping_rf['andhra chilli chicken']]])

In [60]:
predicted3

array([[0.1, 0.9]])

In [61]:
predicted3 =model3.predict_proba([[le_time_mapping['breakfast'],le_dish_mapping_rf['berryblast']]])

In [62]:
predicted3

array([[0.6, 0.4]])

In [64]:
#user_df

In [65]:
######### based on day ##############

In [66]:
list5 = zip(day_encd,veg_encd)
features=list(list5)

In [67]:
model4 = RandomForestClassifier()
model4.fit(features,liked_encd)

C:\Users\mahaj\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [78]:
predicted4 =model4.predict_proba([[le_day_mapping['tue'],le_veg_mapping['no']]])

In [79]:
predicted4

array([[0.54916667, 0.45083333]])

In [73]:
user_df[user_df['day'] == 'tue']

user           dish_ordered  day       time  veg   place liked
12314  user_1      spicy crispy corn  tue      lunch  yes  office    no
12383  user_1                  ladoo  tue     dinner  yes  office    no
13137  user_1             hash brown  tue      lunch  yes  office   yes
13487  user_1       ice cream sundae  tue      lunch  yes  office   yes
13820  user_1     rich chicken broth  tue     dinner   no  office   yes
20062  user_1        afghani biryani  tue     dinner  yes    home    no
20449  user_1  stuffed chicken pizza  tue      lunch   no    home    no
21194  user_1             lamb chops  tue     dinner   no  office    no
21622  user_1           falafel pita  tue  breakfast  yes  office    no
22569  user_1             pane pizza  tue     dinner  yes    home   yes
28396  user_1           thai noodles  tue      lunch  yes    home   yes
29790  user_1         potato krisper  tue  breakfast  yes  office   yes
29964  user_1       chicken sausages  tue  breakfast   no  office   yes
31234  user_1                khichda  tue     dinner  yes  office   yes
31372  user_1            lime mojito  tue     dinner  yes  office    no
37351  user_1             roast pork  tue  breakfast   no    home    no

In [85]:
recommend

{'andhra chilli chicken': 0.4999999999887494,
 'berryblast': 0.4999999999887494,
 'rich chicken broth': 1.582079721785505e-11,
 'smoked chicken sandwich': 6.5950894874877284e-12,
 'chicken frankie': 8.64369043533659e-14}

In [75]:
veg_list = ['berryblast','paneer tikka']
non_veg_list = ['andhra chilli chicken','rich chicken broth','smoked chicken sandwich','chicken frankie']

In [81]:
predicted4[0][0]

0.5491666666666667

In [88]:
new_recommend = {}
if (predicted4[0][0] > 0.5):
    for key in recommend:
        if key in veg_list:
            new_recommend[key] = recommend[key]
            
else:
    new_recommend = recommend
            

In [89]:
new_recommend

{'berryblast': 0.4999999999887494}